name: CD Pipeline - Auto Deploy

on:
  workflow_run:
    workflows: ["CI Pipeline - PHP Lint & Test"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy lên máy chủ AWS
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: 🚀 Tự động kéo code và Deploy
      run: |
        echo "Di chuyển vào thư mục code chính của dự án..."
        cd /home/ubuntu/NTK---SS207
        
        echo "Kéo code mới nhất từ Github..."
        git pull origin main
        
        echo "Cập nhật và khởi động lại website..."
        docker compose up -d --build
        
        echo "Chạy file run_migration.php..."
        docker compose cp run_migration.php php:/var/www/html/run_migration.php
        docker compose exec -T php php /var/www/html/run_migration.php
        docker compose exec -T php rm /var/www/html/run_migration.php
        
        echo "Dọn dẹp rác Docker để nhẹ máy..."
        docker image prune -f
        
        echo "✅ Hoàn tất quá trình Deploy tự động!"
